#!/bin/sh
# setting up cron jobs
echo "*/30 * * * *  /home/zenith71/.local/bin/notify_update" | crontab -
# making directories
mkdir -p ~/pix ~/dl ~/mc ~/stuff ~/.cache/zsh
# cloning the dotfiles repo and moving it to ~/.config
git clone https://github.com/71zenith/dotfiles.git ~/dotfiles
cp -r ~/dotfiles/. ~/.config/
rm -rf ~/dotfiles
# cloning the scripts repo to ~/.local
git clone https://github.com/71zenith/scripts.git ~/.local/
# cloning a bunch of repo
cd ~/stuff
git clone https://github.com/brodierobertson/dotfiles brodie
git clone https://github.com/lukesmithxyz/voidrice luke
git clone https://github.com/71zenith/autoarch
git clone https://github.com/71zenith/st
git clone https://github.com/71zenith/71zenith profile
git clone https://github.com/71zenith/71zenith.github.io startpage
git clone https://github.com/71zenith/slock
git clone https://github.com/71zenith/dmenu
git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
# compiling clipmenu
cd /tmp
git clone https://github.com/cdown/clipmenu
cd clipmenu
doas make install
# compiling mpv-mpris
cd /tmp
git clone https://github.com/hoyon/mpv-mpris
cd mpv-mpris
doas make install
# setting mpv-discord
cd /tmp
git clone https://github.com/tnychn/mpv-discord.git
cd mpv-discord
./install_linux.sh
sed 's/^binary_path.*/binary_path=\/home\/zenith71\/\.config\/mpv\/discord/' ~/.config/mpv/script-opts/discord.conf -i
# setting up the url for push
cd ~/stuff/autoarch
git remote set-url origin git@github.com:71zenith/autoarch
cd ~/stuff/startpage
git remote set-url origin git@github.com:71zenith/71zenith.github.io
# compiling dmenu
cd ~/stuff/dmenu
git remote set-url origin git@github.com:71zenith/dmenu
make
doas make install

# compiling slock
cd ~/stuff/slock
git remote set-url origin git@github.com:71zenith/slock
make
doas make install

# compiling st
cd ~/stuff/st
git remote set-url origin git@github.com:71zenith/st
make
doas make install
# setting up the origin for push
cd ~/.config
git remote set-url origin git@github.com:71zenith/dotfiles
cd ~/.local
git remote set-url origin git@github.com:71zenith/scripts
cd ~/stuff/profile
git remote set-url origin git@github.com:71zenith/71zenith
