#! /bin/sh

# setting the locale and timezone
ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
# setting the tty font
echo "FONT=ter-122n" > /etc/vconsole.conf
# setting the hostname
echo "levi" >> /etc/hostname
# setting the hosts file
echo -e "127.0.0.1    localhost\n::1          localhost\n127.0.1.1    levi" >> /etc/hosts
# setting up doas
echo "permit :wheel
permit nopass :wheel" >> /etc/doas.conf
# setting up systemd-boot
bootctl install
echo -e "default arch.conf\ntimeout 0" > /boot/loader/loader.conf
echo -e "title   Arch Linux\nlinux   /vmlinuz-linux-lts\ninitrd  /amd-ucode.img\ninitrd  /initramfs-linux-lts.img\noptions root=\"LABEL=Arch\" resume=\"LABEL=Swap\" rw" > /boot/loader/entries/arch.conf
# enabling networkmanager and cronie
systemctl enable NetworkManager
systemctl enable cronie.service
# adding the user and assigning groups
useradd -m zenith71 -G wheel,audio,video
# adding chaotic-aur repo and downloading packages
pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
pacman-key --lsign-key FBA220DFC880C036
pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
sed -e 's/CheckSpace/#CheckSpace/' -e 's/#ParallelDownloads\ =\ 5/ParallelDownloads = 10\nILoveCandy/' -e 's/#Color/Color/' -e 's/#VerbosePkgLists/VerbosePkgLists/' -e '$a [chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist' -i /etc/pacman.conf
pacman -Sy --noconfirm zoom polybar lf starship-git neovim-plug brave-bin alacritty-git neovide-git picom-ibhagwan-git fish-autopair
yes | pacman -S libxft-bgra
# setting my mkinitcpio for hibernate feature
sed -e 's/^HOOKS.*/HOOKS=(base udev autodetect keyboard modconf block filesystems resume fsck)/' -e 's/vim.*/vim:ft=sh/' -i /etc/mkinitcpio.conf
mkinitcpio -p linux-lts
# downloading and putting xorg.conf to /etc/X11
curl -L https://github.com/71zenith/autoarch/raw/master/xorg.conf > /etc/X11/xorg.conf
# asking for password
passwd
passwd zenith71
# downloading post post install script and putting it in home folder of user
curl -L https://github.com/71zenith/autoarch/raw/master/postpost > /home/zenith71/postpost
# running the script as the user
su -c "sh /home/zenith71/postpost" zenith71
# changing the default shell of user to fish
chsh zenith71 -s /bin/fish
# cleanup
rm -rf /home/zenith71/{.bash_history,.bash_profile,.bash_logout,.bashrc,postpost}
