#!/bin/sh
# setting up cron jobs
echo "*/30 * * * *  /home/zenith71/.local/bin/notify_update" | crontab -
# making directories
mkdir -p ~/pix ~/dl ~/mc ~/stuff
# cloning the dotfiles repo and moving it to ~/.config
git clone https://github.com/71zenith/dotfiles.git ~/dotfiles
cp -r ~/dotfiles/. ~/.config/
rm -rf ~/dotfiles
# linking zshenv to the home directory
ln -s ~/.config/zsh/.zshenv .zshenv
# cloning the scripts repo to ~/.local
git clone https://github.com/71zenith/scripts.git ~/.local/
# cloning a bunch of repo
cd ~/stuff
git clone https://github.com/brodierobertson/dotfiles brodie
git clone https://github.com/lukesmithxyz/voidrice luke
git clone https://gitlab.com/dwt1/dotfiles.git dt
git clone https://github.com/71zenith/autoarch
git clone https://github.com/71zenith/st
git clone https://github.com/71zenith/71zenith.github.io startpage
git clone https://github.com/71zenith/slock
git clone https://github.com/71zenith/dmenu
# compiling clipmenu
cd /tmp
git clone https://github.com/cdown/clipmenu
cd clipmenu
doas make install
# setting up the url for push
cd ~/stuff/autoarch
git remote set-url origin git@github.com:71zenith/autoarch
cd ~/stuff/startpage
git remote set-url origin git@github.com:71zenith/71zenith.github.io
# compiling dmenu
cd ~/stuff/dmenu
git remote set-url origin git@github.com:71zenith/dmenu
make
doas make install

# compiling slock
cd ~/stuff/slock
git remote set-url origin git@github.com:71zenith/slock
make
doas make install

# compiling st
cd ~/stuff/st
git remote set-url origin git@github.com:71zenith/st
make
doas make install
# setting up the origin for push
cd ~/.config
git remote set-url origin git@github.com:71zenith/dotfiles
cd ~/.local
git remote set-url origin git@github.com:71zenith/scripts
# installing plugins for nvim
nvim "+PlugInstall | qa"
